# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02507e9cea190ff9165f9fc4889101d94ef91acf320099902b529eee4779bbf222254d568f774a02a38777c34880e2def0e7c22770e0671ad792ad1c37bda0f6

test:
  secret_key_base: bf5572a72a592c7297be40922ca3e2c041b0996646fd8709cc0a9f9d574164d67881906e7dd8819861210ad909df7a03bdef2da6d7d30db5008d7b37da00e825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
